import os, sys

base_path = os.path.dirname(__file__)
sys.path.append(os.path.abspath(os.path.join(base_path, '..')))

from sqlalchemy import MetaData, Table, Column, Integer, String, Float, TIMESTAMP, ForeignKey, BigInteger, DateTime


MAGPHYS_NN_METADATA_old = MetaData()
MAGPHYS_NN_METADATA = MetaData()

# FIT file names -> database names
median_output_parameter_name_map = {
    'ager': 'ager',
    'tau_V': 'tau_V',
    'agem': 'agem',
    'tlastb': 'tlastb',
    'M(stars)': 'Mstars',
    'sfr29': 'sfr29',
    'xi_PAH^tot': 'xi_PAHtot',
    'f_mu(SFH)': 'f_muSFH',
    'fb17': 'fb17',
    'fb16': 'fb16',
    'T_C^ISM': 'T_CISM',
    'Ldust': 'Ldust',
    'mu_parameter': 'mu_parameter',
    'xi_C^tot': 'xi_Ctot',
    'xi_W^tot': 'xi_Wtot',
    'f_mu(IR)': 'f_muIR',
    'fb18': 'fb18',
    'fb19': 'fb19',
    'T_W^BC': 'T_WBC',
    'SFR_0.1Gyr': 'SFR_0_1Gyr',
    'fb29': 'fb29',
    'sfr17': 'sfr17',
    'sfr16': 'sfr16',
    'sfr19': 'sfr19',
    'sfr18': 'sfr18',
    'tau_V^ISM': 'tau_VISM',
    'sSFR_0.1Gyr': 'sSFR_0_1Gyr',
    'metalicity Z/Zo': 'metalicity_Z_Z0',
    'M(dust)': 'Mdust',
    'xi_MIR^tot': 'xi_MIRtot',
    'tform': 'tform',
    'gamma': 'gamma'
}

# FIT file names -> database names
best_fit_output_parameter_name_map = {
    'fmu(SFH)': 'fmuSFH',
    'fmu(IR)': 'fmuIR',
    'mu': 'mu',
    'tauv': 'tauv',
    'sSFR': 'sSFR',
    'M*': 'M_asterisk',
    'Ldust': 'Ldust',
    'T_W^BC': 'T_WBC',
    'T_C^ISM': 'T_CISM',
    'xi_C^tot': 'xi_Ctot',
    'xi_PAH^tot': 'xi_PAHtot',
    'xi_MIR^tot': 'xi_MIRtot',
    'xi_W^tot': 'xi_Wtot',
    'tvism': 'tvism',
    'Mdust': 'Mdust',
    'SFR': 'SFR'
}

NN_TRAIN_old = Table('nn_train',
                     MAGPHYS_NN_METADATA_old,
                 Column('train_id', Integer, primary_key=True, autoincrement=True),
                 Column('run_id', String(30)),
                 Column('filename', String(200)),
                 Column('last_updated', TIMESTAMP),
                 Column('redshift', Float),
                 Column('galaxy_number', Integer),
                 Column('input', Integer, ForeignKey('input.input_id')),
                 Column('input_snr', Integer, ForeignKey('input.input_id')),

                 Column('input_Jy', Integer, ForeignKey('input_Jy.input_Jy_id')),
                 Column('input_Jy_snr', Integer, ForeignKey('input_Jy.input_Jy_id')),

                 Column('output_median', Integer, ForeignKey('median_output.median_output_id')),
                 Column('output_best_fit', Integer, ForeignKey('best_fit_output.best_fit_output_id')),
                 Column('output_best_fit_model', Integer, ForeignKey('best_fit_model_output.best_fit_model_id')),
                 Column('output_best_fit_inputs', Integer, ForeignKey('best_fit_output_input.best_fit_output_input_id')),
                 )

INPUT_old = Table('input',
                  MAGPHYS_NN_METADATA_old,
              Column('input_id', Integer, primary_key=True, autoincrement=True),
              Column('type', String(20)),
              Column('fuv', Float),
              Column('nuv', Float),
              Column('u', Float),
              Column('g', Float),
              Column('r', Float),
              Column('z', Float),
              Column('Z_', Float),
              Column('Y', Float),
              Column('J', Float),
              Column('H', Float),
              Column('K', Float),
              Column('WISEW1', Float),
              Column('WISEW2', Float),
              Column('WISEW3', Float),
              Column('WISEW4', Float),
              Column('PACS100', Float),
              Column('PACS160', Float),
              Column('SPIRE250', Float),
              Column('SPIRE350', Float),
              Column('SPIRE500', Float)
              )

INPUT_JY_old = Table('input_Jy',
                     MAGPHYS_NN_METADATA_old,
                 Column('input_Jy_id', Integer, primary_key=True, autoincrement=True),
                 Column('type', String(30)),
                 Column('fuv', Float),
                 Column('nuv', Float),
                 Column('u', Float),
                 Column('g', Float),
                 Column('r', Float),
                 Column('Unknown', Float),
                 Column('z', Float),
                 Column('Z_', Float),
                 Column('Y', Float),
                 Column('J', Float),
                 Column('H', Float),
                 Column('K', Float),
                 Column('WISEW1', Float),
                 Column('WISEW2', Float),
                 Column('WISEW3', Float),
                 Column('WISEW4', Float),
                 Column('PACS100', Float),
                 Column('PACS160', Float),
                 Column('SPIRE250', Float),
                 Column('SPIRE350', Float),
                 Column('SPIRE500', Float),
                 )

MEDIAN_OUTPUT_old = Table('median_output',
                          MAGPHYS_NN_METADATA_old,
                      Column('median_output_id', Integer, primary_key=True, autoincrement=True),
                      Column('ager', Float),
                      Column('tau_V', Float),
                      Column('agem', Float),
                      Column('tlastb', Float),
                      Column('Mstars', Float),
                      Column('sfr29', Float),
                      Column('xi_PAHtot', Float),
                      Column('f_muSFH', Float),
                      Column('fb17', Float),
                      Column('fb16', Float),
                      Column('T_CISM', Float),
                      Column('Ldust', Float),
                      Column('mu_parameter', Float),
                      Column('xi_Ctot', Float),
                      Column('xi_Wtot', Float),
                      Column('f_muIR', Float),
                      Column('fb18', Float),
                      Column('fb19', Float),
                      Column('T_WBC', Float),
                      Column('SFR_0_1Gyr', Float),
                      Column('fb29', Float),
                      Column('sfr17', Float),
                      Column('sfr16', Float),
                      Column('sfr19', Float),
                      Column('sfr18', Float),
                      Column('tau_VISM', Float),
                      Column('sSFR_0_1Gyr', Float),
                      Column('metalicity_Z_Z0', Float),
                      Column('Mdust', Float),
                      Column('xi_MIRtot', Float),
                      Column('tform', Float),
                      Column('gamma', Float)
                      )

BEST_FIT_OUTPUT_old = Table('best_fit_output',
                            MAGPHYS_NN_METADATA_old,
                        Column('best_fit_output_id', Integer, primary_key=True, autoincrement=True),
                        Column('fmuSFH', Float),
                        Column('fmuIR', Float),
                        Column('mu', Float),
                        Column('tauv', Float),
                        Column('sSFR', Float),
                        Column('m_asterisk', Float),
                        Column('Ldust', Float),
                        Column('T_WBC', Float),
                        Column('T_CISM', Float),
                        Column('xi_Ctot', Float),
                        Column('xi_PAHtot', Float),
                        Column('xi_MIRtot', Float),
                        Column('xi_Wtot', Float),
                        Column('tvism', Float),
                        Column('Mdust', Float),
                        Column('SFR', Float),
                        )


BEST_FIT_OUTPUT_INPUT_old = Table('best_fit_output_input',
                                  MAGPHYS_NN_METADATA_old,
                              Column('best_fit_output_input_id', Integer, primary_key=True, autoincrement=True),
                              Column('fuv', Float),
                              Column('nuv', Float),
                              Column('u', Float),
                              Column('g', Float),
                              Column('r', Float),
                              Column('z', Float),
                              Column('Z_', Float),
                              Column('Y', Float),
                              Column('J', Float),
                              Column('H', Float),
                              Column('K', Float),
                              Column('WISEW1', Float),
                              Column('WISEW2', Float),
                              Column('WISEW3', Float),
                              Column('WISEW4', Float),
                              Column('PACS100', Float),
                              Column('PACS160', Float),
                              Column('SPIRE250', Float),
                              Column('SPIRE350', Float),
                              Column('SPIRE500', Float)
                              )

BEST_FIT_MODEL_old = Table('best_fit_model_output',
                           MAGPHYS_NN_METADATA_old,
                       Column('best_fit_model_id', Integer, primary_key=True, autoincrement=True),
                       Column('i_sfh', Float),
                       Column('i_ir', Float),
                       Column('chi2', Float),
                       Column('redshift', Float)
                       )

# --------------------------------------- NEW DATABASE DEFINITIONS-----------------------------------------
NN_TRAIN = Table('nn_train',
                 MAGPHYS_NN_METADATA,
                 Column('galaxy_id', Integer, primary_key=True, autoincrement=True),
                 Column('redshift', Float),
                 Column('run_id', String(30)),
                 Column('fit_filename', String(200)),
                 Column('run_filename', String(200)),
                 )

INPUT = Table('input',
              MAGPHYS_NN_METADATA,
              Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
              Column('fuv', Float),
              Column('nuv', Float),
              Column('u', Float),
              Column('g', Float),
              Column('r', Float),
              Column('i', Float),
              Column('z', Float),
              Column('Z_', Float),
              Column('Y', Float),
              Column('J', Float),
              Column('H', Float),
              Column('K', Float),
              Column('WISEW1', Float),
              Column('WISEW2', Float),
              Column('WISEW3', Float),
              Column('WISEW4', Float),
              Column('PACS100', Float),
              Column('PACS160', Float),
              Column('SPIRE250', Float),
              Column('SPIRE350', Float),
              Column('SPIRE500', Float),
              Column('fuv_snr', Float),
              Column('nuv_snr', Float),
              Column('u_snr', Float),
              Column('g_snr', Float),
              Column('r_snr', Float),
              Column('i_snr', Float),
              Column('z_snr', Float),
              Column('Z__snr', Float),
              Column('Y_snr', Float),
              Column('J_snr', Float),
              Column('H_snr', Float),
              Column('K_snr', Float),
              Column('WISEW1_snr', Float),
              Column('WISEW2_snr', Float),
              Column('WISEW3_snr', Float),
              Column('WISEW4_snr', Float),
              Column('PACS100_snr', Float),
              Column('PACS160_snr', Float),
              Column('SPIRE250_snr', Float),
              Column('SPIRE350_snr', Float),
              Column('SPIRE500_snr', Float),
              )

INPUT_JY = Table('input_Jy',
                 MAGPHYS_NN_METADATA,
                 Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
                 Column('fuv', Float),
                 Column('nuv', Float),
                 Column('u', Float),
                 Column('g', Float),
                 Column('r', Float),
                 Column('i', Float),
                 Column('z', Float),
                 Column('Z_', Float),
                 Column('Y', Float),
                 Column('J', Float),
                 Column('H', Float),
                 Column('K', Float),
                 Column('WISEW1', Float),
                 Column('WISEW2', Float),
                 Column('WISEW3', Float),
                 Column('WISEW4', Float),
                 Column('PACS100', Float),
                 Column('PACS160', Float),
                 Column('SPIRE250', Float),
                 Column('SPIRE350', Float),
                 Column('SPIRE500', Float),
                 Column('fuv_snr', Float),
                 Column('nuv_snr', Float),
                 Column('u_snr', Float),
                 Column('g_snr', Float),
                 Column('r_snr', Float),
                 Column('i_snr', Float),
                 Column('z_snr', Float),
                 Column('Z__snr', Float),
                 Column('Y_snr', Float),
                 Column('J_snr', Float),
                 Column('H_snr', Float),
                 Column('K_snr', Float),
                 Column('WISEW1_snr', Float),
                 Column('WISEW2_snr', Float),
                 Column('WISEW3_snr', Float),
                 Column('WISEW4_snr', Float),
                 Column('PACS100_snr', Float),
                 Column('PACS160_snr', Float),
                 Column('SPIRE250_snr', Float),
                 Column('SPIRE350_snr', Float),
                 Column('SPIRE500_snr', Float),
                 )

MEDIAN_OUTPUT = Table('median_output',
                      MAGPHYS_NN_METADATA,
                      Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
                      Column('ager', Float),
                      Column('tau_V', Float),
                      Column('agem', Float),
                      Column('tlastb', Float),
                      Column('Mstars', Float),
                      Column('sfr29', Float),
                      Column('xi_PAHtot', Float),
                      Column('f_muSFH', Float),
                      Column('fb17', Float),
                      Column('fb16', Float),
                      Column('T_CISM', Float),
                      Column('Ldust', Float),
                      Column('mu_parameter', Float),
                      Column('xi_Ctot', Float),
                      Column('xi_Wtot', Float),
                      Column('f_muIR', Float),
                      Column('fb18', Float),
                      Column('fb19', Float),
                      Column('T_WBC', Float),
                      Column('SFR_0_1Gyr', Float),
                      Column('fb29', Float),
                      Column('sfr17', Float),
                      Column('sfr16', Float),
                      Column('sfr19', Float),
                      Column('sfr18', Float),
                      Column('tau_VISM', Float),
                      Column('sSFR_0_1Gyr', Float),
                      Column('metalicity_Z_Z0', Float),
                      Column('Mdust', Float),
                      Column('xi_MIRtot', Float),
                      Column('tform', Float),
                      Column('gamma', Float)
                      )

BEST_FIT_OUTPUT = Table('best_fit_output',
                        MAGPHYS_NN_METADATA,
                        Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
                        Column('fmuSFH', Float),
                        Column('fmuIR', Float),
                        Column('mu', Float),
                        Column('tauv', Float),
                        Column('sSFR', Float),
                        Column('m_asterisk', Float),
                        Column('Ldust', Float),
                        Column('T_WBC', Float),
                        Column('T_CISM', Float),
                        Column('xi_Ctot', Float),
                        Column('xi_PAHtot', Float),
                        Column('xi_MIRtot', Float),
                        Column('xi_Wtot', Float),
                        Column('tvism', Float),
                        Column('Mdust', Float),
                        Column('SFR', Float),
                        )


BEST_FIT_HISTOGRAM = Table('best_fit_histogram',
                           MAGPHYS_NN_METADATA,
                           Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
                           Column('fuv', Float),
                           Column('nuv', Float),
                           Column('u', Float),
                           Column('g', Float),
                           Column('r', Float),
                           Column('i', Float),
                           Column('z', Float),
                           Column('Z_', Float),
                           Column('Y', Float),
                           Column('J', Float),
                           Column('H', Float),
                           Column('K', Float),
                           Column('WISEW1', Float),
                           Column('WISEW2', Float),
                           Column('WISEW3', Float),
                           Column('WISEW4', Float),
                           Column('PACS100', Float),
                           Column('PACS160', Float),
                           Column('SPIRE250', Float),
                           Column('SPIRE350', Float),
                           Column('SPIRE500', Float)
                           )

BEST_FIT_MODEL = Table('best_fit_model',
                       MAGPHYS_NN_METADATA,
                       Column('galaxy_id', Integer, ForeignKey('nn_train.galaxy_id'), primary_key=True, autoincrement=True),
                       Column('i_sfh', Float),
                       Column('i_ir', Float),
                       Column('chi2', Float),
                       Column('redshift', Float)
                       )